### ISSUE TITLE
Error when running make

### ISSUE THREAD

**Issue by cartheur** [prime6809/DragonDOS#1]
In debian11, running `make` gives the following error:

```
lwasm -9 -r -I defs -DDragon -oroms/ddos10.rom -llist/ddos10.lst ddos12.asm 
Cannot open include file 'basictokens.asm': No such file or directory
make: *** [Makefile:17: ddos10] Error 1
```

**Comment by prime6809** [comment]
Can you try renameing BasicTokens.asm to basictokens.asm in the defs directory (you may also need to do the same to BasicDefs.asm and WDdefs.asm). If that works I'll update the project, I developed mostly under Windows which doesn't care about filename case, but Linux of course does :)

Cheers.

Phill.

**Comment by cartheur** [comment]
To note that changing the filenames to all lowercase was the solution.
